### ISSUE TITLE
Did not find port

### ISSUE THREAD

**Issue by just4give** [QuickLogic-Corp/qorc-sdk#100]
Hi,
I am trying to upload the hello world program. This is my first time using QuickFeather board. I am running on Mac OS. I was able to compile the code and generate bin file but when trying to flash, I am getting below error as in the screen shot. I am connecting the board using micro-usb cable. Can anyone help me to troubleshoot ? 

<img width="1266" alt="Screen Shot 2021-02-03 at 1 35 00 PM" src="https://user-images.githubusercontent.com/9275193/106794429-d566b300-6626-11eb-90da-fc7a2e3a4cc0.png">

**Comment by gmartin102** [comment]
Hi - Most likely this is a permissions issue with the port not having sufficient permission for users to open.  The best test of this is to try the command as sudo.  If that works then it is a permissions issue.

**Comment by just4give** [comment]
Tried sudo and USB Adapter as well but no luck. Any other thoughts ? Anyone got it working on Mac?

<img width="1669" alt="Screen Shot 2021-02-03 at 10 59 58 PM" src="https://user-images.githubusercontent.com/9275193/106843249-9743b080-6673-11eb-935d-53a7dc89aa70.png">

**Comment by just4give** [comment]
Was able to flash the program. I had to use cu.xxxx instead of tty.xxx like 

`qfprog --port /dev/cu.usbmodem143201 --mode m4 --m4app output/bin/qf_helloworldsw.bin`

<img width="1669" alt="Screen Shot 2021-02-03 at 10 59 58 PM" src="https://user-images.githubusercontent.com/9275193/106845134-42eeff80-6678-11eb-93d4-c6f6bd820d28.png">

Going to install Putty on mac to test the output.

**Comment by just4give** [comment]
I am all set. 
<img width="770" alt="Screen Shot 2021-02-04 at 10 56 26 AM" src="https://user-images.githubusercontent.com/9275193/106923440-12d94800-66dc-11eb-99b8-b42e436c5944.png">

**Comment by timsaxe** [comment]
That will be a different device since there is a different USB device ID for the programming vs serial communication

**Comment by tcal-x** [comment]
Hi @timsaxe , thanks!   I hope the info gets added to the docs to make it easier for the next MacOS user.

**Comment by just4give** [comment]
The other one with tty.xxx  .... for flashing I had to use cu.xxx and for putty tty.xxx with baud rate 115200...

**Comment by timsaxe** [comment]
Curious how you track this down on a mac.  On windows I run an app called device manager a look at the ‘com ports’ section.  When I plug in QF a new com port shows up and I know that is the serial port, and when I reset and bring it up in program mode that com port disappears and a different ports shows up which I then know is the programming port.  This also helps when I have more than one QF and am trying to work out which port goes with which device.

Is there a similar process that you used on a mac?

Which reminds me of a further question, in order for documentation to be useful it has to be where people naturally look for it.  Where do you generally look for answers when you have a question like this?  Github doc, github issues, forum, readthedocs, …?

**Comment by just4give** [comment]
I actually did a old school process :) went into /dev folder and listed the devices issuing `ls -lrt` , then plugged in QF board and issued same command again ... new port showed up at the bottom and I new that's the one I just plugged in. There must be a better way to do this but at least worked for me for the time being.
