### ISSUE TITLE
Environment setup script fails if SDK is checked out using git

### ISSUE THREAD

**Issue by whatnick** [QuickLogic-Corp/qorc-sdk#114]
If git protocol is used to checkout the repository the hard-coded remote URL's fail to detect this and environment setup fails. I have this fixed locally with another nested if. Will submit a PR to fix shortly.

**Comment by coolbreeze413** [comment]
Reviewed the way we were using the envsetup.sh, and now ensure that the script can be sourced from anywhere, but will always work relative to qorc-sdk dir, hence removing the need for these checks, making it more robust.
Please open a new issue if you see problems with the latest master.
