### ISSUE TITLE
s3-gateware not published yet ?

### ISSUE THREAD

**Issue by Ruinland** [QuickLogic-Corp/qorc-sdk#28]
Hi,

I see this [commit](https://github.com/QuickLogic-Corp/qorc-sdk/commit/c14bfb4 ) adds s-gateware sumodule.
Yet the [repo](https://github.com/QuickLogic-Corp/s3-gateware) is not accessible.

So should users stick to v1.1.0 for now?

Thanks for the great project and board,
Ruinland

**Comment by murthyvedula** [comment]
Thank you for the feedback. Dependency on the s3-gateware sub-module is now removed.
