### ISSUE TITLE
application repos

### ISSUE THREAD

**Issue by timsaxe** [QuickLogic-Corp/qorc-sdk#48]
today we have qf_apps dir, qf_testapps dir, qf_vr_apps dir, and I can imagine more.  I am thinking that we should have a separate repo for qf_testapps (it can be a submodule) so that we do not burden every user with the testapps.  They can load them if they wish, or not.  That way we don't have to worry about how many testapps we create.

I think we should also have a repo for example applications, perhaps qf_example_apps.  This would be a place for more complex apps that the simple lessons in qf_apps (perhaps we should rename qf_apps to qf_starter_apps).

**Comment by coolbreeze413** [comment]
separate repos for qorc-testapps and qorc-example-apps were added as submodule in qorc-sdk, hence closing this issue.
