### ISSUE TITLE
includes do not track move to a different folder

### ISSUE THREAD

**Issue by timsaxe** [QuickLogic-Corp/qorc-sdk#70]
config-GCC.mk has:
export INCLUDE_DIRS=-I"$(PROJ_DIR)" \
                 -I"$(PROJ_ROOT)/qf_apps/$(PROJ_NAME)/inc" \

the qf_apps makes it fail when a project is copied from one directory (qf_apps in this case) to another (qf_testapps in my case)

Seems like we need to replace qf_apps with $(SOMETHING)

**Comment by coolbreeze413** [comment]
This was fixed with using $APP_DIR/inc instead and should not be a problem anymore.
