### ISSUE TITLE
helloworldsw fails to build

### ISSUE THREAD

**Issue by timsaxe** [QuickLogic-Corp/qorc-sdk#93]
cloned qorc-sdk, cd qf_apps/qf_helloworldssw/GCC_Projects
make fails with 'gateware.h: no such file or directory'

I believe this is due to the refactoring to use eos_xyz_fpga.h

A core question is why the CI didn't catch this?

**Comment by timsaxe** [comment]
Ah, probably forgot to load some submodule...

**Comment by cbc02009** [comment]
@timsaxe How did you manage to solve this? I'm having the same issue and I can't seem to figure it out.

**Comment by timsaxe** [comment]
trying to recreate, but I just changed machines and that means I keeping finding more stuff that needs to be installed ... but when you cloned  qorc-sdk did you do a recursive clone?  I think that's what I forgot to do.

**Comment by cbc02009** [comment]
Yup, that was exactly it. Stupid mistake on my part. Thanks!
